#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "Usage: killAll <process to kill name>"
    exit
fi

out=`ps -elf | grep -i "$1 " | grep -v grep`

while read -r line
do

while true; do
  # (1) prompt user, and read command line argument
  pname=`echo $line | awk '{print substr($0, index($0,$15))}'`
  pid=`echo $line | awk '{print $4}'`
  read -u 3 -p "Kill this process (\"$pname\", $pid) ? " answer

  # (2) handle the input we were given
  case $answer in
   ([yY]* ) kill $pid
            break;;
   ([nN]* ) break;;
   (* ) echo "Please use Y or N.";;
  esac
done

    
done 3<&0  <<<"$out"
